Erro = type: KeyError | message: 'status' | trace: [{'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\websocket\\_app.py', 'name': '_callback', 'lineno': 488}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'on_message', 'lineno': 9593}] | time: 27/02/2023 18:00:14 
Erro = type: UnboundLocalError | message: cannot access local variable 'votes' where it is not associated with a value | trace: [{'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\websocket\\_app.py', 'name': '_callback', 'lineno': 488}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'on_message', 'lineno': 9572}] | time: 27/02/2023 18:02:51 
Erro = type: UnboundLocalError | message: cannot access local variable 'embed' where it is not associated with a value | trace: [{'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\websocket\\_app.py', 'name': '_callback', 'lineno': 488}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'on_message', 'lineno': 9265}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'send_discord_webhook', 'lineno': 715}] | time: 27/02/2023 18:07:19 
Erro = type: MissingSchema | message: Invalid URL '': No scheme supplied. Perhaps you meant http://? | trace: [{'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\websocket\\_app.py', 'name': '_callback', 'lineno': 488}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'on_message', 'lineno': 9278}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'send_discord_webhook', 'lineno': 716}, {'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\discord_webhook\\webhook.py', 'name': 'execute', 'lineno': 435}, {'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\discord_webhook\\webhook.py', 'name': 'api_post_request', 'lineno': 388}, {'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\requests\\api.py', 'name': 'post', 'lineno': 115}, {'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\requests\\api.py', 'name': 'request', 'lineno': 59}, {'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\requests\\sessions.py', 'name': 'request', 'lineno': 573}, {'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\requests\\sessions.py', 'name': 'prepare_request', 'lineno': 484}, {'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\requests\\models.py', 'name': 'prepare', 'lineno': 368}, {'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\requests\\models.py', 'name': 'prepare_url', 'lineno': 439}] | time: 27/02/2023 18:08:53 
Erro = type: UnboundLocalError | message: cannot access local variable 'votes' where it is not associated with a value | trace: [{'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\websocket\\_app.py', 'name': '_callback', 'lineno': 488}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'on_message', 'lineno': 9611}] | time: 28/02/2023 09:15:28 
Erro = type: UnboundLocalError | message: cannot access local variable 'poll_status' where it is not associated with a value | trace: [{'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\websocket\\_app.py', 'name': '_callback', 'lineno': 488}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'on_message', 'lineno': 9655}] | time: 28/02/2023 09:18:16 
Erro = type: UnboundLocalError | message: cannot access local variable 'current_id' where it is not associated with a value | trace: [{'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\websocket\\_app.py', 'name': '_callback', 'lineno': 488}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'on_message', 'lineno': 9655}] | time: 28/02/2023 09:20:16 
Erro = type: AttributeError | message: module 'eel' has no attribute 'pool' | trace: [{'filename': 'C:\\Users\\jhefe\\AppData\\Roaming\\Python\\Python311\\site-packages\\websocket\\_app.py', 'name': '_callback', 'lineno': 488}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'on_message', 'lineno': 9672}] | time: 28/02/2023 11:47:45 
Erro = type: TypeError | message: the JSON object must be str, bytes or bytearray, not dict | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'commands_py', 'lineno': 1842}, {'filename': 'C:\\Program Files\\Python311\\Lib\\json\\__init__.py', 'name': 'loads', 'lineno': 339}] | time: 02/03/2023 12:04:02 
Erro = type: UnboundLocalError | message: cannot access local variable 'aliases' where it is not associated with a value | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'command_fallback', 'lineno': 8912}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'commands_module', 'lineno': 7676}] | time: 02/03/2023 12:04:02 
Erro = type: UnboundLocalError | message: cannot access local variable 'aliases' where it is not associated with a value | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'command_fallback', 'lineno': 8916}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'commands_module', 'lineno': 7680}] | time: 02/03/2023 12:07:23 
Erro = type: IndexError | message: list index out of range | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'command_fallback', 'lineno': 8934}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'commands_module', 'lineno': 7626}] | time: 02/03/2023 12:38:11 
Erro = type: IndexError | message: list index out of range | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'command_fallback', 'lineno': 8935}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'commands_module', 'lineno': 7627}] | time: 02/03/2023 12:40:35 
